### ISSUE TITLE
Not installed

### ISSUE THREAD

**Issue by byeongill** [NatalieKAndersson/DEVOLUTION#1]
Hi

My R version 4.1.2
Bioconductor version 3.14
BiocManager::install("DEVOLUTION")
![image](https://user-images.githubusercontent.com/82578252/147449349-969fea1e-0476-4056-941d-07e454ceb372.png)

So, I search for DEVOLUTION at Bioconductor homepage. however,  I cant find DEVOLUTION.
How install this tools ?

Thanks

**Comment by NatalieKAndersson** [comment]
Hello byeongill!

Thank you for your comment. You are correct. The best way to get started with DEVOLUTION is actually to first download the script "DEVOLUTION_1.1.R", which includes all you need.

1. Install the dependencies, if they are not already installed on your computer.
2. Import your own daya under "Files to be analyzed".
3. Run the functions splitdata followed by DEVOLUTION to obtain the event matrix.

Also, do not hesitate to ask more questions if you have any. You can also contact me at natalie.andersson@med.lu.se.

Best Regards
Natalie
